### ISSUE TITLE
[epic][docs] Docs Overhaul

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1425]
Epic for the docs overhaul work in CY24:

- [ ] **Grid & layout**
  - [ ] Discovery on grid, layout and spacing
    - [ ] Create grid, layout and spacing styles for design system
  - [ ] Update pages with better content design (e.g. column structure, etc.)
- [ ] **Typography**
  - [ ] Create typography and base styles for design system
- [ ] **CSS standardization**
  - [ ] Gut/clean up CSS and create a CSS subsystem for the docs site
- [ ] **Template files standardization**
  - [ ] Switch NJK to WEBC for layout
  - [ ] Clean up template files
- [ ] **Wayfinding improvements**
  - [ ] Table of Contents on pages (list of links at top for easy win)
    - [ ] Discovery on Jump Links (outside layout) vs. TOC (at top of layout)
  - [ ] Side Nav element (new)
  - [ ] Categorization for components (e.g. containers, actions, visualization, etc.)
  - [ ] "Also Known As" (i.e. keywords) for helping users find elements (e.g. "tag" vs "label")
  - [ ] Next/Previous page links
  - [ ] GitHub links
    - [ ] Repo link in nav
    - [ ] Edit this page link on pages
    - [ ] Component source link
- [ ] **Page visual improvements**
  - [ ] Overview page
  - [ ] Make Props/Attr/Etc as a table
  - [ ] Best practices (i.e. this/not this) improvements
- [ ] **Demo improvements**
  - [ ] Build better Playground
    - [ ] View full demo link
  - [ ] Finish Code Block extensions
      - [ ] Design updates
      - [ ] Add show more/code disclosure
  - [ ] Relocate Demo as own "tab" (i.e. playground w/ knobs)
  - [ ] Sample component as replacement on Overview playground (i.e. live component embedded in page)
    - [ ] View demo tab link
- [ ] **Pattern pages improvements**
  - [ ] Add pattern pages for certain elements
  - [ ] Pattern help component pages (link to pattern pages)
- [ ] **Customization help**
  - [ ] Discovery on how to provide clearer info on tokens, CSS vars and shadow parts
- [ ] **Updating/adding sections**
  - [ ] About
  - [ ] Get started
  - [ ] Accessibility
  - [ ] Contributing
  - [ ] Team Support / Help page
- [ ] **Component statuses**
  - [ ] [Improve component status](https://github.com/RedHat-UX/red-hat-design-system/issues/1268)
- [ ] **Search**
  - [ ] Add site search
- [ ] **Theme toggle**
  - [ ] Discovery on user agent preference w/ page-level theming
  - [ ] Add page-level theming to design system
  - [ ] Add theme toggle to docs site

**Comment by markcaron** [comment]
@coreyvickery @marionnegp as promised, here are a handful of issues that needs design work first, while we get more direction from the DPO on the DPO dependent stuff.

### Quick wins
- #1433 
- #1440
- #1441
- #1442 

### Others
- #1434 
- #1329 
- #1438 
- #1449 
- #1450 

Plus, there's all the updating/adding pages & sections stuff we're already working on.

**Comment by mfwells** [comment]
Adding a link to the /demo page as well as /demo/variants would be extremely useful for all Elements. ie: 
https://ux.redhat.com/elements/card/demo/variants/

**Comment by hellogreg** [comment]
reopen if needed
