### ISSUE TITLE
[docs] move playground to code tab

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1452]
_This may be a duplicate issue or one of many RFEs or Bugs out there. If so, let's make this an Epic to track everything._

Our current live demo needs some improvements, including load time.

Related issues:

- [ ] View full demo link — [1451](https://github.com/RedHat-UX/red-hat-design-system/issues/1451)
- [ ] Relocate Demo as own "tab" (i.e. playground w/ knobs) — [1453](https://github.com/RedHat-UX/red-hat-design-system/issues/1453)
- [ ] Bug: `<rh-playground>` external content included in demo editor — [1255](https://github.com/RedHat-UX/red-hat-design-system/issues/1255)

### Current look
<img width="1019" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/2f31fe01-899d-4d3d-85e0-c2391961d563">
