### ISSUE TITLE
[docs bug] Minor edits to repo status table and checklist on elements pages

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1577]
### Describe the bug

Continuation of [#1502](https://github.com/RedHat-UX/red-hat-design-system/pull/1502).

Minor edits to repo status table and checklist on elements pages.

## Status table
- [x] Remove the `Responsive` tag completely (@markcaron Please confirm this is okay.)
- [x] Change `webRH` to `WebRH`

## Status checklist
- [x] Adjust table column widths: `Property`: 20%, `Status`: 20%, and `Meaning`: 60%
- [x] Remove `Responsive` row completely (@markcaron Please confirm this is okay.)
- [x] WebRH row: Reference the table below for the correct checklist text. Right now, it has the same text as the RH Elements row.

### Figma library

| Status | Text |
| - | - |
| Planned | Component should be added to the Figma library at a later date |
| In progress | Component will be added to the Figma library when finished |
| Ready | Component is available in the Figma library |
| Deprecated | Component was removed from the Figma library |
| N/A | Not planned, not available, or does not apply |

### RH Elements

| Status | Text |
| - | - |
| Planned | Component should be added to the RH Elements repo at a later date |
| In progress | Component will be added to the RH Elements repo when finished |
| Ready | Component is available in the RH Elements repo |
| Deprecated | Component is no longer available in the RH Elements repo |
| N/A | Not planned, not available, or does not apply |

### WebRH

| Status | Text |
| - | - |
| Planned | Component should be added to the WebRH repo at a later date |
| In progress | Component will be added to the WebRH repo when finished |
| Ready | Component is available in the WebRH repo |
| Deprecated | Component is no longer available in the WebRH repo |
| N/A | Not planned, not available, or does not apply |

### Which Component?

Repo status table and checklist on elements pages

### Steps to reproduce

Look at the [status table](https://ux.redhat.com/elements/accordion/#status) or [status checklist](https://ux.redhat.com/elements/accordion/#status-checklist) on any element page.

### Expected behaviour

Read edits above.

### Operating System (OS)

iOS, macOS, Linux, Windows

### Browser

Chrome, Safari, Safari iOS, Microsoft Edge, Firefox

**Comment by markcaron** [comment]
@coreyvickery @diwanshi, yes we need to remove the `Responsive` columns from each of the tables.
