### ISSUE TITLE
[chore] <rh-footer> dev handoff checklist

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#308]
## Outstanding todos before dev handoff is complete.

- [x] Fix #307 
- [x] Cut a new release `beta.5`
- [x] Update README.md docs that with up to date code examples.
- [x] Update codepen.io demo with latest release code.
- [x] Update application demo with latest release code.
- [x] Make sure all links and docs are correct in the [launch doc](https://docs.google.com/document/d/11G8L7CuXAYnZDaU6RtLCnv0K1NXeDtEfvpRLKTYk908/edit#)
- [x] Add rh-footer and spandx to the System UX Discovery agenda for 5/25

**Comment by bennypowers** [comment]
@heyMP I've got an updated codepen here: https://codepen.io/bennyp/pen/RwQjWWX?editors=1100
and I have a branch for the app demo, but I don't have permissions to the repo. I sent a PR from a fork, but why don't we also transfer that repo to the RedHat-UX org?

**Comment by bennypowers** [comment]
For readme content, see https://github.com/RedHat-UX/red-hat-design-system/pull/324

**Comment by heyMP** [comment]
New codepen forked from @bennypowers example: https://codepen.io/heyMP/pen/PoQOWzq
New application demo: https://github.com/RedHat-UX/rh-footer-demo
